name: Cyclomatic TS Action

description: Cyclomatic-TS takes a temporary state in software construction by performing static analysis on the codebase and uploads it to storage for future analysis

inputs:
  working_directory:
    description: target directory for analysis
  github_token:
    description: GitHub Token
  event:
    description: GitHub Event
  ecma_script_target:
    description: ScriptTarget as defined in TypeScript (e.g. ES2018, ES2022, ESNext, etc.)

runs:
  using: 'node16'
  main: 'dist/index.js'
  post-if: 'success()'
